import { GridLayout, SocialPlatform } from './types'

export const GRID_LAYOUTS: GridLayout[] = [
  {
    id: '1-single',
    name: 'Single',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '1-portrait',
    name: 'Portrait',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '1-square',
    name: 'Square',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '1-landscape',
    name: 'Landscape',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '1-wide',
    name: 'Panoramic',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '1-story',
    name: 'Instagram Story',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '1-instagram-post',
    name: 'Instagram Post',
    photoCount: 1,
    gridTemplate: '1fr',
    areas: ['a'],
    aspectRatio: '4/5',
    platforms: ['instagram'],
  },
  
  {
    id: '2-horizontal',
    name: 'Side by Side',
    photoCount: 2,
    gridTemplate: '1fr 1fr',
    areas: ['a b'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '2-vertical',
    name: 'Stacked',
    photoCount: 2,
    gridTemplate: '1fr 1fr / 1fr',
    areas: ['a', 'b'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '2-left-large',
    name: 'Left Focus',
    photoCount: 2,
    gridTemplate: '2fr 1fr',
    areas: ['a b'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '2-right-large',
    name: 'Right Focus',
    photoCount: 2,
    gridTemplate: '1fr 2fr',
    areas: ['a b'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '2-top-large',
    name: 'Top Focus',
    photoCount: 2,
    gridTemplate: '2fr 1fr / 1fr',
    areas: ['a', 'b'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '2-bottom-large',
    name: 'Bottom Focus',
    photoCount: 2,
    gridTemplate: '1fr 2fr / 1fr',
    areas: ['a', 'b'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '2-square',
    name: 'Square Split',
    photoCount: 2,
    gridTemplate: '1fr 1fr',
    areas: ['a b'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  
  {
    id: '3-row',
    name: 'Three Across',
    photoCount: 3,
    gridTemplate: '1fr 1fr 1fr',
    areas: ['a b c'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '3-column',
    name: 'Three Down',
    photoCount: 3,
    gridTemplate: '1fr 1fr 1fr / 1fr',
    areas: ['a', 'b', 'c'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '3-left-stack',
    name: 'Left with Stack',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 2fr 1fr',
    areas: ['a a', 'b c'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '3-right-stack',
    name: 'Right with Stack',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b b', 'a c c'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '3-top-row',
    name: 'Top with Bottom',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '3-bottom-row',
    name: 'Bottom with Top',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c c'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '3-center-focus',
    name: 'Center Focus',
    photoCount: 3,
    gridTemplate: '1fr 2fr 1fr',
    areas: ['a b c'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '3-pyramid',
    name: 'Pyramid',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '3-l-shape',
    name: 'L-Shape',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'a c'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  
  {
    id: '4-grid',
    name: 'Classic Grid',
    photoCount: 4,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '4-row',
    name: 'Four Across',
    photoCount: 4,
    gridTemplate: '1fr 1fr 1fr 1fr',
    areas: ['a b c d'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '4-column',
    name: 'Four Down',
    photoCount: 4,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr',
    areas: ['a', 'b', 'c', 'd'],
    aspectRatio: '9/21',
    platforms: ['instagram']
  },
  {
    id: '4-left-focus',
    name: 'Left Hero',
    photoCount: 4,
    gridTemplate: '1fr 1fr 1fr / 2fr 1fr',
    areas: ['a b', 'a c', 'a d'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '4-right-focus',
    name: 'Right Hero',
    photoCount: 4,
    gridTemplate: '1fr 1fr 1fr / 1fr 2fr',
    areas: ['a b', 'c b', 'd b'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '4-top-bottom',
    name: 'Top & Bottom Pairs',
    photoCount: 4,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '4-center-focus',
    name: 'Center Spotlight',
    photoCount: 4,
    gridTemplate: '1fr 2fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c', 'd d'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '4-t-shape',
    name: 'T-Shape',
    photoCount: 4,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a a', 'b c d'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '4-corners',
    name: 'Wide Grid',
    photoCount: 4,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  
  {
    id: '5-plus',
    name: 'Plus Sign',
    photoCount: 5,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b a', 'c d e', 'a b a'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '5-top-one',
    name: 'Top Hero',
    photoCount: 5,
    gridTemplate: '2fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a a a', 'b c d e'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '5-left-two',
    name: 'Left Column',
    photoCount: 5,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e e'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '5-grid-top',
    name: 'Grid with Top',
    photoCount: 5,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c', 'd e'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '5-center',
    name: 'Center Focus',
    photoCount: 5,
    gridTemplate: '1fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e e'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '5-pyramid',
    name: 'Pyramid',
    photoCount: 5,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c', 'd e'],
    aspectRatio: '4/5',
    platforms: ['instagram'],
  },
  {
    id: '5-scattered',
    name: 'Asymmetric',
    photoCount: 5,
    gridTemplate: '1fr 1fr / 2fr 1fr 1fr',
    areas: ['a a b', 'c d e'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '5-bottom-row',
    name: 'Bottom Row',
    photoCount: 5,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a b', 'c d e'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  
  {
    id: '6-grid',
    name: 'Classic 2x3',
    photoCount: 6,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '6-grid-vertical',
    name: 'Classic 3x2',
    photoCount: 6,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d', 'e f'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '6-two-rows',
    name: 'Two Rows',
    photoCount: 6,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '6-left-hero',
    name: 'Left Hero',
    photoCount: 6,
    gridTemplate: '1fr 1fr 1fr / 2fr 1fr 1fr',
    areas: ['a b c', 'a d e', 'a f f'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '6-center-large',
    name: 'Center Large',
    photoCount: 6,
    gridTemplate: '1fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '6-bookends',
    name: 'Bookends',
    photoCount: 6,
    gridTemplate: '1fr 1fr / 2fr 1fr 1fr 2fr',
    areas: ['a b c d', 'a e f d'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '6-top-bottom',
    name: 'Top-Bottom Focus',
    photoCount: 6,
    gridTemplate: '2fr 1fr 1fr 2fr / 1fr 1fr',
    areas: ['a a', 'b c', 'd d', 'e f'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '6-scattered',
    name: 'Mixed Sizes',
    photoCount: 6,
    gridTemplate: '1fr 1fr 1fr / 2fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f f f'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  
  {
    id: '7-flower',
    name: 'Flower Pattern',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g g g'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '7-top-hero',
    name: 'Top Hero',
    photoCount: 7,
    gridTemplate: '2fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a a', 'b c d', 'e f g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '7-left-column',
    name: 'Left Column',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'a d e', 'f g g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '7-center-focus',
    name: 'Center Focus',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g e g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '7-rows',
    name: 'Three Rows',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '7-asymmetric',
    name: 'Asymmetric',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 2fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '7-bottom-row',
    name: 'Bottom Wide',
    photoCount: 7,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g g g'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  
  {
    id: '8-grid',
    name: 'Classic 4x2',
    photoCount: 8,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c d', 'e f g h'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '8-grid-tall',
    name: 'Classic 2x4',
    photoCount: 8,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d', 'e f', 'g h'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '8-center-large',
    name: 'Center Quad',
    photoCount: 8,
    gridTemplate: '1fr 2fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g h h'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '8-sides',
    name: 'Side Columns',
    photoCount: 8,
    gridTemplate: '1fr 1fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g e h'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '8-top-bottom',
    name: 'Top & Bottom',
    photoCount: 8,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c d', 'e f g h'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '8-mixed',
    name: 'Mixed Sizes',
    photoCount: 8,
    gridTemplate: '1fr 1fr 1fr / 2fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g h'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '8-corners',
    name: 'Corner Focus',
    photoCount: 8,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd d d', 'e f g', 'h h h'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  
  {
    id: '9-grid',
    name: 'Perfect Grid',
    photoCount: 9,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '9-center-large',
    name: 'Center Hero',
    photoCount: 9,
    gridTemplate: '1fr 2fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '9-corners-large',
    name: 'Corner Focus',
    photoCount: 9,
    gridTemplate: '2fr 1fr 2fr / 2fr 1fr 2fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '9-cross',
    name: 'Cross Pattern',
    photoCount: 9,
    gridTemplate: '1fr 1fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '9-rows',
    name: 'Three Rows',
    photoCount: 9,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '9-columns',
    name: 'Three Columns',
    photoCount: 9,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '9-pyramid',
    name: 'Pyramid',
    photoCount: 9,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a b b', 'c d e e', 'f g h i'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '9-frame',
    name: 'Frame',
    photoCount: 9,
    gridTemplate: '1fr 2fr 1fr / 1fr 2fr 1fr',
    areas: ['a b c', 'd e f', 'g h i'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },

  // ─── 10 photos ──────────────────────────────────────────────────────────────
  {
    id: '10-grid-2x5',
    name: 'Two Rows',
    photoCount: 10,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d e', 'f g h i j'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '10-grid-5x2',
    name: 'Five Rows',
    photoCount: 10,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d', 'e f', 'g h', 'i j'],
    aspectRatio: '9/21',
    platforms: ['instagram']
  },
  {
    id: '10-top-hero',
    name: 'Top Hero',
    photoCount: 10,
    gridTemplate: '2fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a a', 'b c d', 'e f g', 'h i j'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '10-mosaic',
    name: 'Mosaic',
    photoCount: 10,
    gridTemplate: '1fr 1fr 1fr 1fr / 2fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g g', 'h i j'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '10-classic-grid',
    name: 'Classic Grid',
    photoCount: 10,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d', 'e f', 'g h', 'i j'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },

  // ─── 11 photos ──────────────────────────────────────────────────────────────
  {
    id: '11-rows-3-4-4',
    name: 'Three Rows',
    photoCount: 11,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c c', 'd e f g', 'h i j k'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '11-left-hero',
    name: 'Left Hero',
    photoCount: 11,
    gridTemplate: '1fr 1fr 1fr 1fr / 2fr 1fr 1fr 1fr',
    areas: ['a b c d', 'a e f g', 'a h i j', 'a k k k'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '11-mixed',
    name: 'Mixed Sizes',
    photoCount: 11,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g h', 'i j k'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '11-top-bottom',
    name: 'Top & Bottom',
    photoCount: 11,
    gridTemplate: '2fr 1fr 1fr 1fr 2fr / 1fr 1fr 1fr',
    areas: ['a a a', 'b c d', 'e f g', 'h i j', 'k k k'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },

  // ─── 12 photos ──────────────────────────────────────────────────────────────
  {
    id: '12-grid-3x4',
    name: 'Classic 3×4',
    photoCount: 12,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c d', 'e f g h', 'i j k l'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '12-grid-4x3',
    name: 'Classic 4×3',
    photoCount: 12,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g h i', 'j k l'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '12-grid-2x6',
    name: 'Wide 2×6',
    photoCount: 12,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d e f', 'g h i j k l'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '12-hero-mosaic',
    name: 'Hero Mosaic',
    photoCount: 12,
    gridTemplate: '2fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a b b', 'c d e f', 'g h i j', 'k k l l'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '12-mixed',
    name: 'Mixed Sizes',
    photoCount: 12,
    gridTemplate: '1fr 1fr 1fr 1fr / 2fr 1fr 1fr 1fr',
    areas: ['a a b c', 'd e f g', 'h i j j', 'k k l l'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },

  // ─── 13 photos ──────────────────────────────────────────────────────────────
  {
    id: '13-top-hero',
    name: 'Top Hero',
    photoCount: 13,
    gridTemplate: '2fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a a a', 'b c d e', 'f g h i', 'j k l m'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },
  {
    id: '13-asymmetric',
    name: 'Asymmetric',
    photoCount: 13,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c c', 'd e f g', 'h i j k', 'l l m m'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '13-mixed',
    name: 'Mixed Rows',
    photoCount: 13,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d e', 'f g g h h', 'i j k l m'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '13-mosaic',
    name: 'Mosaic',
    photoCount: 13,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a a b', 'c d e', 'f g h', 'i j j', 'k l m'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },

  // ─── 14 photos ──────────────────────────────────────────────────────────────
  {
    id: '14-grid-2x7',
    name: 'Two Rows',
    photoCount: 14,
    gridTemplate: '1fr 1fr / 1fr 1fr 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d e f g', 'h i j k l m n'],
    aspectRatio: '21/9',
    platforms: ['youtube'],
  },
  {
    id: '14-grid-7x2',
    name: 'Seven Rows',
    photoCount: 14,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr 1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d', 'e f', 'g h', 'i j', 'k l', 'm n'],
    aspectRatio: '9/21',
    platforms: ['instagram']
  },
  {
    id: '14-hero-grid',
    name: 'Hero + Grid',
    photoCount: 14,
    gridTemplate: '2fr 2fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a a a', 'a a a a', 'b c d e', 'f g h i', 'j k l m', 'n n n n'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '14-mixed',
    name: 'Mixed Rows',
    photoCount: 14,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d d', 'e f g h h', 'i j k l m', 'n n n n n'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },

  // ─── 15 photos ──────────────────────────────────────────────────────────────
  {
    id: '15-grid-3x5',
    name: 'Classic 3×5',
    photoCount: 15,
    gridTemplate: '1fr 1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a b c d e', 'f g h i j', 'k l m n o'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '15-grid-5x3',
    name: 'Classic 5×3',
    photoCount: 15,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr',
    areas: ['a b c', 'd e f', 'g h i', 'j k l', 'm n o'],
    aspectRatio: '9/16',
    platforms: ['instagram', 'facebook', 'youtube'],
  },
  {
    id: '15-hero-grid',
    name: 'Hero + Grid',
    photoCount: 15,
    gridTemplate: '2fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a b b', 'c d e f', 'g h i j', 'k l m n', 'o o o o'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '15-pyramid',
    name: 'Pyramid',
    photoCount: 15,
    gridTemplate: '1fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a a a b b', 'c d e f f', 'g h i j k', 'l l m n n', 'o o o o o'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },

  // ─── 16 photos ──────────────────────────────────────────────────────────────
  {
    id: '16-grid-4x4',
    name: 'Classic 4×4',
    photoCount: 16,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c d', 'e f g h', 'i j k l', 'm n o p'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '16-wide-grid',
    name: 'Wide 4×4',
    photoCount: 16,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a b c d', 'e f g h', 'i j k l', 'm n o p'],
    aspectRatio: '16/9',
    platforms: ['youtube', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '16-hero-grid',
    name: 'Hero + Grid',
    photoCount: 16,
    gridTemplate: '2fr 1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr',
    areas: ['a a b b', 'c d e f', 'g h i j', 'k l m n', 'o o p p'],
    aspectRatio: '3/4',
    platforms: ['instagram'],
  },
  {
    id: '16-mixed',
    name: 'Mixed Sizes',
    photoCount: 16,
    gridTemplate: '1fr 1fr 1fr 1fr / 1fr 1fr 1fr 1fr 1fr',
    areas: ['a a b c d', 'e f g h h', 'i j k l m', 'n n o o p'],
    aspectRatio: '4/3',
    platforms: ['facebook'],
  },

  // ─── Social media specific layouts ──────────────────────────────────────────
  {
    id: '2-instagram-post',
    name: 'Instagram Post Split',
    photoCount: 2,
    gridTemplate: '1fr 1fr',
    areas: ['a b'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '2-instagram-portrait',
    name: 'Instagram Portrait Split',
    photoCount: 2,
    gridTemplate: '1fr 1fr',
    areas: ['a b'],
    aspectRatio: '4/5',
    platforms: ['instagram'],
  },
  {
    id: '3-instagram-post',
    name: 'Instagram Post Triptych',
    photoCount: 3,
    gridTemplate: '1fr 1fr 1fr',
    areas: ['a b c'],
    aspectRatio: '1/1',
    platforms: ['instagram', 'facebook', 'twitter', 'linkedin'],
  },
  {
    id: '3-instagram-portrait',
    name: 'Instagram Portrait Stack',
    photoCount: 3,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a a', 'b c'],
    aspectRatio: '4/5',
    platforms: ['instagram'],
  },
  {
    id: '4-instagram-post',
    name: 'Instagram Post Grid',
    photoCount: 4,
    gridTemplate: '1fr 1fr / 1fr 1fr',
    areas: ['a b', 'c d'],
    aspectRatio: '4/5',
    platforms: ['instagram'],
  },
]

export function getLayoutsForPhotoCount(count: number): GridLayout[] {
  return GRID_LAYOUTS.filter(layout => layout.photoCount === count)
}

/**
 * Extract unique area names from grid-template-area row strings.
 * e.g. ['a b a', 'c d e', 'a b a'] → ['a', 'b', 'c', 'd', 'e']
 */
export function getUniqueAreaNames(areas: string[]): string[] {
  const seen = new Set<string>()
  const result: string[] = []
  for (const row of areas) {
    for (const name of row.split(' ')) {
      if (!seen.has(name)) {
        seen.add(name)
        result.push(name)
      }
    }
  }
  return result
}

export function getLayoutsForPlatform(platform: SocialPlatform): GridLayout[] {
  return GRID_LAYOUTS.filter(layout => layout.platforms?.includes(platform))
}

export function getLayoutsForPhotoCountAndPlatform(count: number, platform: SocialPlatform | null): GridLayout[] {
  return GRID_LAYOUTS.filter(layout =>
    layout.photoCount === count &&
    (platform === null || layout.platforms?.includes(platform))
  )
}
